import { Header } from "@/components/site/Header";
import { Footer } from "@/components/site/Footer";
import { ExampleGallery } from "@/components/marketing/Examples";
import { Hero } from "@/components/marketing/Hero";
import { Specimens } from "@/components/marketing/Specimens";
import { SectionPhoto } from "@/components/marketing/SectionPhoto";
import { PricingCards } from "@/components/marketing/PricingCards";
import { Reveal } from "@/components/marketing/Reveal";

export default function Home() {
  return (
    <>
      <Header />
      <Hero />

      {/* Examples — light, on paper, so the generated maps read exactly as they will printed */}
      <section id="examples" className="mx-auto max-w-6xl px-5 py-16 lg:py-20">
        <Reveal>
          <SectionHeading
            eyebrow="Examples"
            title="Every map follows real cartographic conventions"
            sub="Generated by the same engine you'll use — equal-area projections, ColorBrewer palettes, honest data classification, and proper map furniture."
          />
        </Reveal>
        <div className="mt-10">
          <ExampleGallery />
        </div>
      </section>

      <Specimens />

      {/* How it works — dark, photo-backed */}
      <section id="how" className="film-grain relative border-b border-room-line bg-room">
        <SectionPhoto src="/media/world-geo.jpg" alt="" className="opacity-70" />
        <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-room via-room/85 to-room" />
        <div className="relative mx-auto max-w-6xl px-5 py-16 lg:py-20">
          <Reveal>
            <SectionHeading dark eyebrow="How it works" title="Four steps to a finished map" />
          </Reveal>
          <ol className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {STEPS.map((s, i) => (
              <Reveal key={i} delay={i * 90} as="li">
                <div className="h-full rounded-[3px] border border-room-line bg-room-2/70 p-6 backdrop-blur-sm">
                  <div className="font-serif text-3xl text-brass">{i + 1}</div>
                  <h3 className="mt-3 font-medium text-paper">{s.title}</h3>
                  <p className="mt-1.5 text-sm text-parchment-muted">{s.body}</p>
                </div>
              </Reveal>
            ))}
          </ol>
        </div>
      </section>

      {/* Why it looks right — split, photo left, checklist right */}
      <section className="relative overflow-hidden border-b border-room-line bg-room">
        <div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 lg:grid-cols-[0.85fr_1.15fr] lg:py-20">
          <Reveal className="relative hidden min-h-[420px] overflow-hidden rounded-[3px] ring-1 ring-room-line lg:block">
            <SectionPhoto src="/media/atlas-gold.jpg" alt="An antique gold-toned map under warm light" />
          </Reveal>
          <div>
            <Reveal>
              <SectionHeading
                dark
                eyebrow="Why it looks right"
                title="Made like a cartographer, not an algorithm"
                sub="The details that separate a professional map from a coloured-in clip-art blob — baked into every export."
              />
            </Reveal>
            <div className="mt-10 grid gap-x-10 gap-y-6 sm:grid-cols-2">
              {PRINCIPLES.map((p, i) => (
                <Reveal key={p.title} delay={i * 60} className="flex gap-4">
                  <Tick />
                  <div>
                    <h3 className="font-medium text-paper">{p.title}</h3>
                    <p className="mt-1 text-sm text-parchment-muted">{p.body}</p>
                  </div>
                </Reveal>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Pricing — dark, earth backdrop */}
      <section id="pricing" className="film-grain relative bg-room">
        <SectionPhoto src="/media/earth-dark.jpg" alt="" className="opacity-45" />
        <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-room via-room/90 to-room" />
        <div className="relative mx-auto max-w-6xl px-5 py-16 lg:py-20">
          <Reveal>
            <SectionHeading dark eyebrow="Pricing" title="Simple, per-map pricing" />
          </Reveal>
          <PricingCards />
          <p className="mt-6 text-center text-sm text-parchment-muted">
            Additional revisions $5 each. No subscription, no account.
          </p>
        </div>
      </section>

      <Footer />
    </>
  );
}

const STEPS = [
  { title: "Describe your map", body: "One prompt — the places, the metric, and the message. Add data if you have it." },
  { title: "Pick a map type", body: "Choose from a gallery of map types, each with a live sample and a recommendation." },
  { title: "Brand it", body: "Add your title, organisation, logo, and a caption." },
  { title: "Preview & download", body: "Tweak, pay $5, and download a print-ready PDF." },
];

const PRINCIPLES = [
  { title: "Equal-area projections", body: "Thematic maps use equal-area projections fitted to your region — never a stretched Web Mercator." },
  { title: "ColorBrewer palettes only", body: "Sequential, diverging, or qualitative schemes chosen to match your data. No rainbow, no neon." },
  { title: "Honest data classification", body: "Quantile, equal-interval, or Jenks natural breaks — so the colours mean something." },
  { title: "Proper map furniture", body: "A real scale bar in kilometres, a discreet north arrow, graticule, neatline, and a labelled legend." },
  { title: "Editorial typography", body: "A serif/grotesque pairing with a clear hierarchy — the way a printed atlas reads." },
  { title: "Figure-ground & restraint", body: "Muted land, quiet ocean, crisp hairlines. The data is the loudest thing on the page." },
];

function SectionHeading({ eyebrow, title, sub, dark }: { eyebrow: string; title: string; sub?: string; dark?: boolean }) {
  return (
    <div className="max-w-2xl">
      <p className={`font-mono-tight text-xs uppercase tracking-wider ${dark ? "text-brass" : "text-accent"}`}>{eyebrow}</p>
      <h2 className={`mt-2 font-serif text-3xl font-semibold tracking-tight ${dark ? "text-paper" : "text-ink"}`}>{title}</h2>
      {sub && <p className={`mt-3 ${dark ? "text-parchment-muted" : "text-muted"}`}>{sub}</p>}
    </div>
  );
}

function Tick() {
  return (
    <svg width={22} height={22} viewBox="0 0 22 22" className="mt-0.5 shrink-0" aria-hidden>
      <circle cx="11" cy="11" r="11" fill="var(--color-brass)" opacity="0.16" />
      <path d="M6.5 11.3l3 3 6-6.4" fill="none" stroke="var(--color-brass)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}
