import { Header } from "@/components/site/Header";
import { Footer } from "@/components/site/Footer";
import { Button } from "@/components/ui/Button";
import { FeaturedMap, ExampleGallery } from "@/components/marketing/Examples";

export default function Home() {
  return (
    <>
      <Header />

      {/* Hero */}
      <section className="paper-grain border-b border-line">
        <div className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-16 lg:grid-cols-2 lg:py-24">
          <div>
            <p className="mb-4 inline-flex items-center gap-2 rounded-full border border-line bg-paper px-3 py-1 text-xs font-medium text-muted">
              <span className="h-1.5 w-1.5 rounded-full bg-accent" />
              Cartography, by design — not AI clip-art
            </p>
            <h1 className="font-serif text-4xl font-semibold leading-[1.1] tracking-tight sm:text-5xl">
              Turn your data into a publication-quality map in&nbsp;60&nbsp;seconds.
            </h1>
            <p className="mt-5 max-w-lg text-lg text-muted">
              Answer a few questions, drop in your data, and download a print-ready PDF that looks
              like a professional cartographer made it — proper projections, real colour ramps, a
              legend that makes sense. <span className="text-ink">$5 a map.</span>
            </p>
            <div className="mt-8 flex flex-wrap items-center gap-3">
              <Button href="/create" size="lg">Create my map</Button>
              <Button href="#examples" variant="secondary" size="lg">See examples</Button>
            </div>
            <p className="mt-4 text-sm text-muted">
              $5 per map · 1 free revision included · no account needed
            </p>
          </div>
          <FeaturedMap />
        </div>
      </section>

      {/* Examples */}
      <section id="examples" className="mx-auto max-w-6xl px-5 py-16 lg:py-20">
        <SectionHeading
          eyebrow="Examples"
          title="Every map follows real cartographic conventions"
          sub="These are generated by the same engine you'll use — equal-area projections, ColorBrewer palettes, data classification, and proper map furniture."
        />
        <div className="mt-10">
          <ExampleGallery />
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="border-y border-line bg-paper-2">
        <div className="mx-auto max-w-6xl px-5 py-16 lg:py-20">
          <SectionHeading eyebrow="How it works" title="Four steps to a finished map" />
          <ol className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {STEPS.map((s, i) => (
              <li key={i} className="rounded-xl border border-line bg-paper p-6">
                <div className="font-serif text-3xl text-accent">{i + 1}</div>
                <h3 className="mt-3 font-medium">{s.title}</h3>
                <p className="mt-1.5 text-sm text-muted">{s.body}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Differentiator */}
      <section className="mx-auto max-w-6xl px-5 py-16 lg:py-20">
        <SectionHeading
          eyebrow="Why it looks right"
          title="Made like a cartographer, not an algorithm"
          sub="The details that separate a professional map from a coloured-in clip-art blob — baked into every export."
        />
        <div className="mt-10 grid gap-x-10 gap-y-6 sm:grid-cols-2">
          {PRINCIPLES.map((p) => (
            <div key={p.title} className="flex gap-4">
              <Tick />
              <div>
                <h3 className="font-medium">{p.title}</h3>
                <p className="mt-1 text-sm text-muted">{p.body}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="border-t border-line bg-paper-2">
        <div className="mx-auto max-w-6xl px-5 py-16 lg:py-20">
          <SectionHeading eyebrow="Pricing" title="Simple, per-map pricing" />
          <div className="mt-10 grid gap-6 lg:grid-cols-3">
            <PriceCard name="Single map" price="$5" featured items={["One print-ready PDF (300 DPI)", "1 free revision included", "A4 or Letter, your choice"]} cta />
            <PriceCard name="3-map pack" price="$12" items={["Three maps — save $3", "1 free revision each", "Use any time"]} />
            <PriceCard name="5-map pack" price="$18" items={["Five maps — save $7", "1 free revision each", "Best for reports & series"]} />
          </div>
          <p className="mt-6 text-center text-sm text-muted">Additional revisions $5 each. No subscription, no account.</p>
        </div>
      </section>

      <Footer />
    </>
  );
}

const STEPS = [
  { title: "Pick your industry", body: "Choose from 24 fields — healthcare, NGO, sport, journalism and more." },
  { title: "Answer a few questions", body: "Five quick choices, plus an optional plain-English description." },
  { title: "Add or generate data", body: "Upload a CSV/Excel, paste a table, or let us generate a sample." },
  { title: "Preview & download", body: "Tweak the furniture, pay $5, and download your PDF." },
];

const PRINCIPLES = [
  { title: "Equal-area projections", body: "Thematic maps use equal-area projections fitted to your region — never a stretched Web Mercator." },
  { title: "ColorBrewer palettes only", body: "Sequential, diverging, or qualitative schemes chosen to match your data. No rainbow, no neon." },
  { title: "Honest data classification", body: "Quantile, equal-interval, or Jenks natural breaks — so the colours mean something." },
  { title: "Proper map furniture", body: "A real scale bar in kilometres, a discreet north arrow, graticule, neatline, and a labelled legend." },
  { title: "Editorial typography", body: "A serif/grotesque pairing with a clear hierarchy — the way a printed atlas reads." },
  { title: "Figure-ground & restraint", body: "Muted land, quiet ocean, crisp hairlines. The data is the loudest thing on the page." },
];

function SectionHeading({ eyebrow, title, sub }: { eyebrow: string; title: string; sub?: string }) {
  return (
    <div className="max-w-2xl">
      <p className="text-xs font-semibold uppercase tracking-wider text-accent">{eyebrow}</p>
      <h2 className="mt-2 font-serif text-3xl font-semibold tracking-tight">{title}</h2>
      {sub && <p className="mt-3 text-muted">{sub}</p>}
    </div>
  );
}

function PriceCard({
  name,
  price,
  items,
  featured,
  cta,
}: {
  name: string;
  price: string;
  items: string[];
  featured?: boolean;
  cta?: boolean;
}) {
  return (
    <div
      className={`rounded-2xl border p-7 ${
        featured ? "border-accent bg-paper shadow-md" : "border-line bg-paper"
      }`}
    >
      <h3 className="font-medium">{name}</h3>
      <p className="mt-2 font-serif text-4xl font-semibold">{price}</p>
      <ul className="mt-5 space-y-2.5 text-sm">
        {items.map((it) => (
          <li key={it} className="flex gap-2.5">
            <Tick small />
            <span>{it}</span>
          </li>
        ))}
      </ul>
      <div className="mt-6">
        <Button href="/create" variant={cta ? "primary" : "secondary"} className="w-full">
          {cta ? "Create my map" : "Choose pack"}
        </Button>
      </div>
    </div>
  );
}

function Tick({ small }: { small?: boolean }) {
  const s = small ? 16 : 22;
  return (
    <svg width={s} height={s} viewBox="0 0 22 22" className="mt-0.5 shrink-0" aria-hidden>
      <circle cx="11" cy="11" r="11" fill="var(--color-accent)" opacity="0.12" />
      <path d="M6.5 11.3l3 3 6-6.4" fill="none" stroke="var(--color-accent)" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}
