"use client";

import { useMemo, useRef, useState } from "react";
import type { FeatureCollection } from "geojson";
import { Button } from "@/components/ui/Button";
import { LOOKS } from "./looks";
import { FontPicker } from "./FontPicker";
import { CartoMap } from "@/components/cartography/CartoMap";
import { useSubdivisions } from "@/components/cartography/useSubdivisions";
import { chooseJoin } from "@/lib/cartography/join";
import { exportSvgToPdf, pagePt } from "@/lib/pdf-client";
import { downloadSvgFile } from "@/lib/svg-download";
import { CHANGES_PER_MAP } from "@/lib/quota-rules";
import { parseMapSpec, type Decision, type MapSpec, type Furniture } from "@/lib/mapspec/schema";
import type { Row } from "@/lib/data/parse";

interface Props {
  geo: FeatureCollection | null;
  spec: MapSpec;
  data: Row[];
  setSpec: (spec: MapSpec) => void;
  onRevise: (text: string) => void;
  onBack: () => void;
  /** Called when the user downloads, so the saved copy matches what they took. */
  onDownloaded: () => void;
  revisionsUsed: number;
  busy: boolean;
  /** Saved to the user's account (false when accounts are off). */
  saved: boolean;
}

const FURNITURE_TOGGLES: { key: keyof Furniture; label: string }[] = [
  { key: "title", label: "Title" },
  { key: "labels", label: "Place names" },
  { key: "legend", label: "Legend" },
  { key: "scalebar", label: "Scale bar" },
  { key: "north_arrow", label: "North arrow" },
  { key: "graticule", label: "Graticule" },
  { key: "caption", label: "Caption" },
  { key: "source", label: "Source line" },
];

const STYLES = LOOKS;

export function PreviewStep({ geo, spec, data, setSpec, onRevise, onBack, onDownloaded, revisionsUsed, busy, saved }: Props) {
  const exportRef = useRef<HTMLDivElement>(null);
  const [revision, setRevision] = useState("");
  const [exporting, setExporting] = useState(false);

  const landscape = spec.page.orientation === "landscape";
  const W = landscape ? 880 : 620;
  const H = Math.round(landscape ? W / Math.SQRT2 : W * Math.SQRT2);
  const pdf = pagePt(spec.page);

  const subdivisions = useSubdivisions(spec, geo);

  // For region maps, how many place names matched a country / province / district?
  const coverage = useMemo(() => {
    const field = spec.data.nameField;
    if (!geo || (spec.mapType !== "choropleth" && spec.mapType !== "footprint") || !field) return null;
    const names = Array.from(new Set(data.map((r) => r[field]).filter((v) => v != null).map(String)));
    const join = chooseJoin(names, geo, subdivisions, spec.geography.level);
    const noun = join.level === "adm1" ? "provinces/states" : join.level === "adm2" ? "districts" : "countries";
    return { total: names.length, matched: names.filter((n) => join.match(n)).length, noun };
  }, [geo, subdivisions, spec.mapType, spec.data.nameField, spec.geography.level, data]);

  const setFurniture = (key: keyof Furniture, value: boolean) =>
    setSpec(parseMapSpec({ ...spec, furniture: { ...spec.furniture, [key]: value } }));

  const setPage = (patch: Partial<MapSpec["page"]>) =>
    setSpec(parseMapSpec({ ...spec, page: { ...spec.page, ...patch } }));

  const downloadSvg = () => {
    const svg = exportRef.current?.querySelector("svg");
    if (!svg) return;
    downloadSvgFile(svg as SVGSVGElement, spec.title);
    onDownloaded();
  };

  const exportPdf = async () => {
    const svg = exportRef.current?.querySelector("svg");
    if (!svg) return;
    setExporting(true);
    try {
      await exportSvgToPdf(svg as SVGSVGElement, spec.page, slug(spec.title), [spec.typography.title, spec.typography.text]);
      onDownloaded();
    } catch {
      /* ignore */
    } finally {
      setExporting(false);
    }
  };

  const applyRevision = () => {
    if (revision.trim()) {
      onRevise(revision.trim());
      setRevision("");
    }
  };

  return (
    <div>
      <h2 className="display text-4xl font-semibold text-ink">Your map</h2>
      <p className="mt-1.5 text-muted">Toggle elements, tweak the page, or ask for a change. Looks good? Download the print-ready PDF. It&apos;s free.</p>

      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_300px]">
        {/* Map */}
        <div>
          <div className="overflow-hidden rounded-xl border border-line bg-paper shadow-sm">
            {geo ? (
              <CartoMap spec={spec} data={data} geo={geo} subdivisions={subdivisions} width={W} height={H} className="h-auto w-full" />
            ) : (
              <div className="aspect-[3/2] w-full animate-pulse bg-paper-2" />
            )}
          </div>
          {spec.decisions?.length ? (
            <DecisionLog decisions={spec.decisions} />
          ) : (
            spec.notes &&
            !/^Generated by/i.test(spec.notes) && (
              <details className="mt-4 rounded-lg border border-line bg-paper px-4 py-3 text-sm" open>
                <summary className="cursor-pointer font-medium text-ink">Why it looks this way</summary>
                <p className="mt-2 leading-relaxed text-muted">{spec.notes}</p>
              </details>
            )
          )}
          {coverage && coverage.matched < coverage.total && (
            <p className="mt-2 text-[13px] text-amber-700">
              Matched {coverage.matched} of {coverage.total} place names to {coverage.noun}. Unmatched places stay uncoloured (shown as “No data”). Check the spelling against official names.
            </p>
          )}
        </div>

        {/* Controls */}
        <aside className="space-y-6">
          <Panel title="Style">
            <div className="grid grid-cols-3 gap-2">
              {STYLES.map((st) => (
                <button
                  key={st.id}
                  type="button"
                  onClick={() => setSpec(parseMapSpec({ ...spec, style: st.id }))}
                  className={`rounded-lg border px-2 py-2 text-left text-sm transition-colors ${
                    spec.style === st.id ? "border-accent bg-accent/10 text-ink" : "border-line text-muted hover:border-accent/50 hover:text-ink"
                  }`}
                >
                  <span className="mb-1.5 block h-7 rounded-md border border-line/60" style={{ background: st.swatch }} />
                  <span className="block font-medium">{st.label}</span>
                  <span className="block text-[11px] leading-tight opacity-80">{st.hint}</span>
                </button>
              ))}
            </div>
          </Panel>

          <Panel title="Fonts">
            <FontPicker
              stacked
              title={spec.typography.title}
              text={spec.typography.text}
              onChange={(f) => setSpec(parseMapSpec({ ...spec, typography: f }))}
            />
          </Panel>

          <Panel title="Map elements">
            <div className="space-y-2">
              {FURNITURE_TOGGLES.map((t) => (
                <Toggle key={t.key} label={t.label} checked={spec.furniture[t.key]} onChange={(v) => setFurniture(t.key, v)} />
              ))}
            </div>
          </Panel>

          <Panel title="Page">
            <div className="space-y-3">
              <Segmented
                value={spec.page.orientation}
                options={[
                  { value: "landscape", label: "Landscape" },
                  { value: "portrait", label: "Portrait" },
                ]}
                onChange={(v) => setPage({ orientation: v as MapSpec["page"]["orientation"] })}
              />
              <Segmented
                value={spec.page.size}
                options={[
                  { value: "A4", label: "A4" },
                  { value: "Letter", label: "Letter" },
                ]}
                onChange={(v) => setPage({ size: v as MapSpec["page"]["size"] })}
              />
            </div>
          </Panel>

          <Panel title="Ask for a change">
            <textarea
              value={revision}
              onChange={(e) => setRevision(e.target.value)}
              rows={3}
              placeholder='e.g. "make it green", "remove the north arrow", "use natural breaks"'
              className="w-full resize-none rounded-lg border border-line bg-paper p-2.5 text-sm outline-none focus:border-accent focus:ring-1 focus:ring-accent"
            />
            <div className="mt-2 flex items-center justify-between">
              <span className="text-xs text-muted">
                {revisionsUsed === 0 ? `Up to ${CHANGES_PER_MAP} changes per map` : `${revisionsUsed} of ${CHANGES_PER_MAP} changes used`}
              </span>
              <Button variant="secondary" size="sm" onClick={applyRevision} disabled={busy || !revision.trim()}>
                {busy ? "Working…" : "Apply"}
              </Button>
            </div>
          </Panel>
        </aside>
      </div>

      <div className="mt-8 flex flex-wrap items-center justify-between gap-3">
        <Button onClick={onBack} variant="ghost">← Back</Button>
        <div className="flex flex-col items-end gap-1.5">
          <div className="flex items-center gap-3">
            <Button onClick={downloadSvg} variant="secondary" disabled={!geo}>
              SVG for designers
            </Button>
            <Button onClick={exportPdf} size="lg" disabled={busy || exporting || !geo}>
              {exporting ? "Preparing PDF…" : "Download PDF"}
            </Button>
          </div>
          <span className="text-xs text-muted">
            Vector PDF for print, no watermark{saved ? " · saved to My maps" : ""}
          </span>
        </div>
      </div>

      {/* Hidden, print-font copy used only for client-side PDF export */}
      {geo && (
        <div
          ref={exportRef}
          aria-hidden
          style={{ position: "fixed", left: -99999, top: 0, opacity: 0, pointerEvents: "none" }}
        >
          <CartoMap spec={spec} data={data} geo={geo} subdivisions={subdivisions} width={pdf.w} height={pdf.h} forPdf />
        </div>
      )}
    </div>
  );
}

const SOURCE: Record<Decision["by"], { label: string; cls: string }> = {
  brief: { label: "Your brief", cls: "bg-atlas-sage/60 text-atlas-forest" },
  data: { label: "Your data", cls: "bg-atlas-green/25 text-atlas-ink" },
  rules: { label: "Rulebook", cls: "bg-atlas-card text-atlas-ink-2 border border-line" },
  ai: { label: "AI cartographer", cls: "bg-atlas-ochre/25 text-atlas-ink" },
  check: { label: "Corrected", cls: "bg-amber-100 text-amber-900" },
};

/** The engine's reasoning, rule by rule, and anything its checks corrected. */
function DecisionLog({ decisions }: { decisions: Decision[] }) {
  const corrected = decisions.filter((d) => d.by === "check").length;
  return (
    <details className="mt-4 rounded-lg border border-line bg-paper px-4 py-3 text-sm" open>
      <summary className="cursor-pointer font-medium text-ink">
        How this map was decided
        <span className="ml-2 font-normal text-muted">
          {decisions.length} decisions{corrected ? ` · ${corrected} corrected by the checks` : " · all checks passed"}
        </span>
      </summary>
      <ol className="mt-3 divide-y divide-line">
        {decisions.map((d, i) => (
          <li key={i} className="grid grid-cols-[auto_1fr] gap-x-3 py-2.5">
            <span className="pt-0.5 tabular-nums text-[11px] text-muted">{d.rule}</span>
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-medium text-ink">{d.topic}:</span>
                <span className="text-ink">{d.choice}</span>
                <span className={`rounded-full px-2 py-0.5 text-[10.5px] font-medium ${SOURCE[d.by].cls}`}>{SOURCE[d.by].label}</span>
              </div>
              <p className="mt-0.5 leading-relaxed text-muted">{d.because}</p>
            </div>
          </li>
        ))}
      </ol>
    </details>
  );
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-line bg-paper p-4">
      <h3 className="text-xs font-semibold text-muted">{title}</h3>
      <div className="mt-3">{children}</div>
    </div>
  );
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <button type="button" onClick={() => onChange(!checked)} className="flex w-full items-center justify-between text-sm">
      <span>{label}</span>
      <span className={`relative h-5 w-9 rounded-full transition-colors ${checked ? "bg-accent" : "bg-line"}`}>
        <span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white transition-all ${checked ? "left-[1.125rem]" : "left-0.5"}`} />
      </span>
    </button>
  );
}

function Segmented({
  value,
  options,
  onChange,
}: {
  value: string;
  options: { value: string; label: string }[];
  onChange: (v: string) => void;
}) {
  return (
    <div className="inline-flex w-full rounded-lg border border-line p-0.5">
      {options.map((o) => (
        <button
          key={o.value}
          type="button"
          onClick={() => onChange(o.value)}
          className={`flex-1 rounded-md px-3 py-1.5 text-sm transition-colors ${
            value === o.value ? "bg-accent text-white" : "text-muted hover:text-ink"
          }`}
        >
          {o.label}
        </button>
      ))}
    </div>
  );
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "cartomapper-map";
}
